config:
	cp redis.conf redis00/ 
	cp redis.conf redis01/ 
	cp redis.conf redis10/ 
	cp redis.conf redis11/ 
	cp redis.conf redis20/ 
	cp redis.conf redis21/ 
	
clear-data:
	rm -rf redis00/data/*
	rm -rf redis01/data/*
	rm -rf redis10/data/*
	rm -rf redis11/data/*
	rm -rf redis20/data/*
	rm -rf redis21/data/*
