nginx-https:
    image: nginx:alpine
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/conf.d:/etc/nginx/conf.d
        - ./conf/certs:/etc/nginx/certs
        - ./html:/usr/share/nginx/html
    ports:
        - 8080:80
        - 8443:443

