FROM elasticsearch:5.6.16-alpine

MAINTAINER	Heropoo "aiyouyou1000@163.com"

RUN elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.16/elasticsearch-analysis-ik-5.6.
16.zip
