version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
#      - ./logs:/var/log/mysql/
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456

        #  adminer:
        #    image: adminer
        #    restart: always
        #    ports:
        #      - 8080:8080
