version: '3.1'
services:
    nginx:
        image: nginx:alpine
        #command: nginx -g 'daemon off;'
        restart: always
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./www:/srv/www
            - ./logs/nginx:/var/log/nginx
        ports:
            - 80:80
    php-fpm:
        image: heropoo/php-fpm-alpine
        restart: always
        volumes:
            - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
            - ./www:/srv/www
